# Generated by Django 5.0.3 on 2024-05-23 20:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hospital",
            old_name="name",
            new_name="namee",
        ),
    ]
